spring.application.name: java-kata-consumer
spring.profiles.active: local

spring:
  config:
    import:
      - monitoring.yml

redis-stream:
  stream-key: submission

---
spring.config.activate.on-profile: local

spring:
  data:
    redis:
      host: ${storage.redis.local-host}
      port: 6379
      timeout: 3000

---
spring.config.activate.on-profile: prod

spring:
  data:
    redis:
      host: ${storage.redis.prod-host}
      port: 6379
      timeout: 3000