spring.config.activate.on-profile: local

spring:
  data:
    redis:
      host: ${storage.redis.local-host}
      port: 6379
      timeout: 3000
      password: ${storage.redis.local-password}
---
spring.config.activate.on-profile: prod

spring:
  data:
    redis:
      host: ${storage.redis.prod-host}
      port: 6379
      timeout: 3000
      password: ${storage.redis.prod-password}