global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9091' ]

  - job_name: 'java-kata-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'docker.for.mac.localhost:8080' ]