spring.config.activate.on-profile: local

spring:
  rabbitmq:
    host: ${message.rabbitmq.local-host}
    port: 5672
    username: ${message.rabbitmq.local-username}
    password: ${message.rabbitmq.local-password}
---
spring.config.activate.on-profile: prod

spring:
  rabbitmq:
    host: ${message.rabbitmq.prod-host}
    port: 5672
    username: ${message.rabbitmq.prod-username}
    password: ${message.rabbitmq.prod-password}