name: CI

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: checkFormat
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for core-api
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./core/core-api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/java-kata-api:latest
            ${{ secrets.DOCKER_USERNAME }}/java-kata-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image for core-worker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./core/core-worker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/java-kata-api:latest
            ${{ secrets.DOCKER_USERNAME }}/java-kata-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max